name: Build and Release

on:
  workflow_dispatch:
  push:
    branches:
      - release

jobs:
  build-and-release:
    runs-on: self-hosted
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust nightly toolchain
        run: |
          rustup toolchain install nightly
          rustup default nightly
          rustup target add x86_64-pc-windows-msvc
        shell: cmd

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Build womp-core
        run: |
          cargo build --release -p womp-core

      - name: Build womp-cli
        run: |
          cargo build --release -p womp-cli

      - name: Install frontend dependencies
        run: |
          cd crates/womp
          npm install

      - name: Create Release
        id: tauri_action
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
        with:
          projectPath: crates/womp
          tagName: v__VERSION__
          releaseName: 'WOMP v__VERSION__'
          releaseBody: |
            # Changelog

            - 

            ---

            See the assets to download this version and install.

            WOMP___VERSION___x64-setup.exe already includes the womp-cli.exe binary.

            If you only need the womp-cli.exe binary, you can download it from the assets by itself.
          releaseDraft: true
          includeUpdaterJson: true
          prerelease: false

      - name: Upload womp-cli.exe to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.tauri_action.outputs.releaseUploadUrl }}
          asset_path: target/release/womp-cli.exe
          asset_name: womp-cli.exe
          asset_content_type: application/octet-stream